### ISSUE TITLE
Fabulous Course - Comment section?

### ISSUE THREAD

**Issue by stiofand** [jacekschae/learn-reagent-course-files#11]
Another Fab course, thanks!

Sorry for the issue, can't seem to find anywhere to add comments!

**Comment by jacekschae** [comment]
Hi there, thanks for your comments -- also noticed via email the message regarding the initial setup. There is [`shadow-cljs quick-start`](https://github.com/thheller/shadow-cljs#quick-start) so that you can utilze `npx create-cljs-project`

Hope that helps, if there would be anything else -- feel free to reach out.
